# deploy.yml
name: 'Function deploy'
description: 'Deploy FaaS functions to the appropriate OpenFaaS environment'
outputs:
  status:
    description: 'Whether the process succeeded or failed'
runs:
  using: 'docker'
  image: 'Dockerfile'