# action.yml
name: 'OpenFaaS deploy action helper'

description: 'Determines the functions which needs to be deployed'

inputs:
  stack-file:
    description: 'stack.yml path'
    default: 'stack.yml'
  force-deploy-functions:
    description: 'Force deploy functions even if nothing is changed in the source code'

outputs:
  functions-to-deploy:
    description: 'List functions for strategy matrix'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.stack-file }}
    - ${{ inputs.force-deploy-functions }}
