# push.yml
name: 'Function push'
description: 'Push FaaS functions to the container registry'
outputs:
  status:
    description: 'Whether the process succeeded or failed'
runs:
  using: 'docker'
  image: 'Dockerfile'